<?xml version="1.0"?>
<package format="3">
  <name>codebotler_amrl_impl</name>
  <version>0.0.0</version>
  <description>The amrl implementation of the codebotler</description>

  <maintainer email="amrl_user@todo.todo">Zichao Hu</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>action_msgs</depend>
  <depend>builtin_interfaces</depend>
  
  <!-- External dependencies -->
  <depend>amrl_msgs</depend>
  <depend>cobot_codebotler_actions</depend>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
